baseURL = "https://darka.github.io"
languageCode = "en-us"
title = "Darius' Code Tinkerings"
theme = "mini"
pygmentsUseClasses = false
pygmentsStyle = "friendly"
googleAnalytics = "UA-199920153-1"
disqusShortname = "darius-code-tinkerings"

[params]
enableGoogleAnalytics = true
enableComments = true
